flake8==3.3.0
pytest==3.1.3
pylidc==0.1.9 # Fixes UnicodeDecodeError in to_volume() (https://github.com/pylidc/pylidc/issues/9)
